image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - apt-get update && apt-get install -y php composer
              - composer install
              - ./vendor/bin/phpunit test

        - step:
            name: Lint
            script:
              - apt-get update && apt-get install -y php composer
              - composer install
              - ./vendor/bin/phplint . --exclude=vendor

  branches:
    master:
      - step:
          name: Deploy a FTP (SSL-CHILE)
          deployment: production
          script:
            - apt-get update && apt-get install -y lftp
            - lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -R ./ /public_html/ssl-chile --delete --verbose --exclude .git --exclude node_modules --exclude vendor --exclude bitbucket-pipelines.yml; quit"